export default {
	// days
	mon: 'Monday',
	tue: 'Tuesday',
	wed: 'Wednesday',
	thu: 'Thursday',
	fri: 'Friday',
	sat: 'Sathurday',
	sun: 'Sunday',
	// months
	january: 'January',
	february: 'February',
	march: 'March',
	april: 'April',
	may: 'May',
	june: 'June',
	july: 'July',
	august: 'August',
	september: 'September',
	october: 'October',
	november: 'November',
	december: 'December',
	//other
	day: 'Day',
	week: 'Week',
	month: 'Month',
	prev: 'Prev',
	today: 'Today',
	next: 'Next',
}