export default {
	mon: 'fMonday',
	tue: 'fTuesday',
	wed: 'fWednesday',
	thu: 'fThursday',
	fri: 'fFriday',
	sat: 'fSathurday',
	sun: 'fSunday',
	january: 'January',
	february: 'February',
	march: 'March',
	april: 'April',
	may: 'May',
	june: 'June',
	july: 'July',
	august: 'August',
	september: 'September',
	october: 'October',
	november: 'November',
	december: 'December',
	//other
	day: 'fDay',
	week: 'Week',
	month: 'Month',
	prev: 'Prev',
	today: 'Today',
	next: 'Next',
}